name: Deploy Angular App to GitHub Pages

on:
    push:
        branches:
            - main  # شاخه‌ای که کد رو push می‌کنی

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 18

            - name: Install dependencies
              run: npm ci

            - name: Build Angular App
              run: npm run build -- --configuration production --base-href /rescue-environment/

            - name: Deploy to GitHub Pages
              uses: peaceiris/actions-gh-pages@v4
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: ./dist/rescue-environment
                  publish_branch: gh-pages
